"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "@/lib/FormContext";
import BlueprintSection from "@/components/BlueprintSection";
import CodeBlock from "@/components/CodeBlock";

export default function BlueprintPage() {
  const router = useRouter();
  const { state, resetForm, hydrated } = useForm();
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (hydrated && !state.blueprint) {
      router.push("/form");
    }
  }, [hydrated, state.blueprint, router]);

  if (!hydrated || !state.blueprint) {
    return null;
  }

  const { blueprint } = state;

  const extractCodeBlocks = (text: string) => {
    const codeBlockRegex = /```(\w+)?\n([\s\S]*?)```/g;
    const parts: Array<{ type: "text" | "code"; content: string; language?: string }> = [];
    let lastIndex = 0;
    let match;

    while ((match = codeBlockRegex.exec(text)) !== null) {
      if (match.index > lastIndex) {
        parts.push({
          type: "text",
          content: text.slice(lastIndex, match.index).trim(),
        });
      }
      parts.push({
        type: "code",
        content: match[2].trim(),
        language: match[1] || "text",
      });
      lastIndex = match.index + match[0].length;
    }

    if (lastIndex < text.length) {
      parts.push({
        type: "text",
        content: text.slice(lastIndex).trim(),
      });
    }

    return parts;
  };

  const handleCopyAll = async () => {
    try {
      await navigator.clipboard.writeText(blueprint.rawResponse);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([blueprint.rawResponse], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "project-blueprint.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleBuildInVSCode = async () => {
    try {
      // First, copy the blueprint to clipboard
      await navigator.clipboard.writeText(blueprint.rawResponse);
      
      // Create a temporary file and download it
      const blob = new Blob([blueprint.rawResponse], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "project-blueprint.md";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      // Wait a moment for the download to start
      await new Promise(resolve => setTimeout(resolve, 500));
      
      // Try to open VS Code
      // User will need to open the downloaded file in VS Code
      const vscodeUrl = "vscode://";
      window.location.href = vscodeUrl;
      
      // Show success message
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch (err) {
      console.error("Failed to build in VS Code:", err);
      // Fallback: just copy to clipboard
      try {
        await navigator.clipboard.writeText(blueprint.rawResponse);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (copyErr) {
        console.error("Failed to copy:", copyErr);
      }
    }
  };

  const handleStartOver = () => {
    resetForm();
    router.push("/");
  };

  return (
    <main className="min-h-screen py-16 md:py-24 px-8 md:px-16">
      <div className="max-w-[760px] mx-auto">
        {/* Header */}
        <div className="mb-16 animate-fade-in">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">✦</span>
            <h1 className="font-serif text-5xl md:text-[56px] leading-tight text-[var(--text-primary)]">
              Your Project
              <br />
              Blueprint
            </h1>
          </div>
          <p className="font-mono text-base text-[var(--text-secondary)]">
            Generated by IBM Bob — ready to copy, download, or customize
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-3 mb-12 animate-fade-in" style={{ animationDelay: "100ms" }}>
          <button
            onClick={handleBuildInVSCode}
            className="px-4 py-2.5 bg-accent text-background border border-accent rounded-[6px] font-mono text-[15px] font-medium hover:bg-accent-hover hover:scale-[1.02] active:scale-[0.98] transition-all duration-150 shadow-sm"
          >
            🚀 Build from Blueprint
          </button>
          <button
            onClick={handleCopyAll}
            className="px-4 py-2.5 bg-surface border border-border rounded-[6px] text-text-primary font-mono text-[15px] hover:border-border-hover hover:scale-[1.02] active:scale-[0.98] transition-all duration-150"
          >
            {copied ? "✓ Copied!" : "Copy full blueprint"}
          </button>
          <button
            onClick={handleDownload}
            className="px-4 py-2.5 bg-surface border border-border rounded-[6px] text-text-primary font-mono text-[15px] hover:border-border-hover hover:scale-[1.02] active:scale-[0.98] transition-all duration-150"
          >
            Download blueprint (.md)
          </button>
          <button
            onClick={handleStartOver}
            className="px-4 py-2.5 bg-transparent border border-border rounded-[6px] text-text-secondary font-mono text-[15px] hover:text-text-primary hover:border-border-hover hover:scale-[1.02] active:scale-[0.98] transition-all duration-150"
          >
            Start over
          </button>
        </div>

        {blueprint.parseFailed && (
          <p
            className="mb-8 font-mono text-sm text-[var(--text-secondary)] border border-[var(--border)] rounded-[var(--radius-card)] px-4 py-3 animate-fade-in"
            style={{ animationDelay: "150ms" }}
          >
            Sections could not be split automatically — showing the full
            blueprint below. Use Copy or Download for the complete markdown.
          </p>
        )}

        <div className="space-y-8">
          {blueprint.summary && (
            <BlueprintSection
              title={
                blueprint.parseFailed
                  ? "Full Blueprint"
                  : "A — Project Summary"
              }
              delay={200}
              content={blueprint.parseFailed ? blueprint.rawResponse : `# A — Project Summary\n\n${blueprint.summary}`}
            >
              <p className="font-mono text-[15px] leading-relaxed whitespace-pre-wrap">
                {blueprint.summary}
              </p>
            </BlueprintSection>
          )}

          {!blueprint.parseFailed && blueprint.techStack && (
            <BlueprintSection
              title="B — Tech Stack"
              delay={280}
              content={`# B — Tech Stack\n\n${blueprint.techStack}`}
            >
              <div className="font-mono text-[15px] leading-relaxed whitespace-pre-wrap">
                {blueprint.techStack}
              </div>
            </BlueprintSection>
          )}

          {!blueprint.parseFailed && blueprint.folderStructure && (
            <BlueprintSection
              title="C — Folder Structure"
              delay={360}
              content={`# C — Folder Structure\n\n${blueprint.folderStructure}`}
            >
              <div className="space-y-4">
                {extractCodeBlocks(blueprint.folderStructure).map((part, idx) =>
                  part.type === "code" ? (
                    <CodeBlock
                      key={idx}
                      code={part.content}
                      language={part.language}
                    />
                  ) : (
                    <p
                      key={idx}
                      className="font-mono text-[15px] leading-relaxed whitespace-pre-wrap"
                    >
                      {part.content}
                    </p>
                  )
                )}
              </div>
            </BlueprintSection>
          )}

          {!blueprint.parseFailed && blueprint.starterFiles && (
            <BlueprintSection
              title="D — Starter Files"
              delay={440}
              content={`# D — Starter Files\n\n${blueprint.starterFiles}`}
            >
              <div className="space-y-4">
                {extractCodeBlocks(blueprint.starterFiles).map((part, idx) =>
                  part.type === "code" ? (
                    <CodeBlock
                      key={idx}
                      code={part.content}
                      language={part.language}
                    />
                  ) : (
                    <p
                      key={idx}
                      className="font-mono text-[15px] leading-relaxed whitespace-pre-wrap"
                    >
                      {part.content}
                    </p>
                  )
                )}
              </div>
            </BlueprintSection>
          )}

          {!blueprint.parseFailed && blueprint.setupChecklist && (
            <BlueprintSection
              title="E — Setup Checklist"
              delay={520}
              content={`# E — Setup Checklist\n\n${blueprint.setupChecklist}`}
            >
              <div className="font-mono text-[15px] leading-relaxed whitespace-pre-wrap">
                {blueprint.setupChecklist}
              </div>
            </BlueprintSection>
          )}
        </div>

        {/* Footer */}
        <div className="mt-16 pt-8 border-t border-[var(--border)] text-center animate-fade-in" style={{ animationDelay: "600ms" }}>
          <p className="font-mono text-sm text-[var(--text-tertiary)] mb-4">
            Generated by IBM Bob | Project Kickstarter
          </p>
          <button
            onClick={handleStartOver}
            className="text-[15px] font-mono text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
          >
            Create another project →
          </button>
        </div>
      </div>
    </main>
  );
}

// Made with Bob
